name: C++ cmake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Test ${{ matrix.build_type }} mode on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Debug, Release]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        path: Catch2
    - name: configure catch2
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCATCH_BUILD_TESTING=OFF
      working-directory: Catch2
    - name: compile and install catch2
      run: sudo cmake --build build/ --target install 
      working-directory: Catch2
      if: matrix.os != 'windows-latest'
    - name: compile and install catch2 (windows)
      run: cmake --build build/ --target install 
      working-directory: Catch2
      if: matrix.os == 'windows-latest'
    - name: cmake ${{ matrix.build_type }}
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: compile
      run: cmake --build build/
    - name: test
      run: |
        pwd
        ls
        ./species_test
      working-directory: speciation/build/tests
      shell: bash
